# Generated by Django 3.1.6 on 2021-02-19 13:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='btc_wallet_balance',
            field=models.DecimalField(decimal_places=10, default=Decimal('0E-10'), max_digits=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)], verbose_name='btc wallet balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='eth_wallet_balance',
            field=models.DecimalField(decimal_places=10, default=Decimal('0E-10'), max_digits=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)], verbose_name='eth wallet balance'),
        ),
    ]
