# Generated by Django 3.1.6 on 2021-02-22 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency_type', models.CharField(choices=[('btc', 'BTC'), ('eth', 'ETH')], max_length=255)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_upated', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('processing', 'PROCESSING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='processing', max_length=255)),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_user', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
