# Generated by Django 3.1.6 on 2021-02-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_ref',
            field=models.CharField(default='demo1234', max_length=255),
        ),
    ]
