# Generated by Django 3.1.6 on 2021-02-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_transaction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency_amount',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
    ]
