# Generated by Django 3.1.6 on 2021-02-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210222_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_ref',
            field=models.CharField(default='demo1234', max_length=255, unique=True),
        ),
    ]
